const STORAGE_KEY='shopping_list_super_v1',THEME_KEY='shopping_list_theme_v1';let deferredPrompt=null;
const els={itemInput:document.getElementById('itemInput'),qtyInput:document.getElementById('qtyInput'),categoryInput:document.getElementById('categoryInput'),storeInput:document.getElementById('storeInput'),priorityInput:document.getElementById('priorityInput'),notesInput:document.getElementById('notesInput'),addBtn:document.getElementById('addBtn'),clearDoneBtn:document.getElementById('clearDoneBtn'),clearAllBtn:document.getElementById('clearAllBtn'),filterStore:document.getElementById('filterStore'),filterCategory:document.getElementById('filterCategory'),searchInput:document.getElementById('searchInput'),showMode:document.getElementById('showMode'),list:document.getElementById('list'),emptyState:document.getElementById('emptyState'),visibleCount:document.getElementById('visibleCount'),selectedStoreText:document.getElementById('selectedStoreText'),totalItems:document.getElementById('totalItems'),doneItems:document.getElementById('doneItems'),pendingItems:document.getElementById('pendingItems'),themeToggle:document.getElementById('themeToggle'),installBtn:document.getElementById('installBtn')};
const demoItems=[{id:uid(),name:'Leite',qty:2,category:'Supermercado',store:'Continente',priority:'Alta',notes:'Sem lactose',done:false,createdAt:new Date().toISOString()},{id:uid(),name:'Pão',qty:1,category:'Padaria',store:'Pingo Doce',priority:'Normal',notes:'',done:false,createdAt:new Date().toISOString()},{id:uid(),name:'Detergente',qty:1,category:'Casa',store:'Lidl',priority:'Baixa',notes:'',done:true,createdAt:new Date().toISOString()}];
let items=loadItems();
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function loadItems(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(Array.isArray(saved)&&saved.length)return saved}catch(e){}localStorage.setItem(STORAGE_KEY,JSON.stringify(demoItems));return demoItems}
function saveItems(){localStorage.setItem(STORAGE_KEY,JSON.stringify(items))}
function applyTheme(){const saved=localStorage.getItem(THEME_KEY)||'dark';document.body.classList.toggle('light',saved==='light');els.themeToggle.textContent=saved==='light'?'☀️':'🌙'}
function toggleTheme(){const current=localStorage.getItem(THEME_KEY)||'dark';localStorage.setItem(THEME_KEY,current==='dark'?'light':'dark');applyTheme()}
function addItem(){const name=els.itemInput.value.trim(),qty=Math.max(1,Number(els.qtyInput.value||1)),category=els.categoryInput.value,store=els.storeInput.value,priority=els.priorityInput.value,notes=els.notesInput.value.trim();if(!name){els.itemInput.focus();return}items.unshift({id:uid(),name,qty,category,store,priority,notes,done:false,createdAt:new Date().toISOString()});saveItems();clearForm();render()}
function clearForm(){els.itemInput.value='';els.qtyInput.value=1;els.categoryInput.value='Supermercado';els.storeInput.value='Continente';els.priorityInput.value='Normal';els.notesInput.value=''}
function toggleDone(id){items=items.map(item=>item.id===id?{...item,done:!item.done}:item);saveItems();render()}
function removeItem(id){items=items.filter(item=>item.id!==id);saveItems();render()}
function clearDone(){items=items.filter(item=>!item.done);saveItems();render()}
function clearAll(){items=[];saveItems();render()}
function getFilters(){return{store:els.filterStore.value,category:els.filterCategory.value,search:els.searchInput.value.trim().toLowerCase(),mode:els.showMode.value}}
function sortItems(list){const o={Alta:0,Normal:1,Baixa:2};return[...list].sort((a,b)=>a.done!==b.done?a.done-b.done:o[a.priority]!==o[b.priority]?o[a.priority]-o[b.priority]:new Date(b.createdAt)-new Date(a.createdAt))}
function filteredItems(){const f=getFilters();return sortItems(items.filter(item=>{if(f.store&&item.store!==f.store)return false;if(f.category&&item.category!==f.category)return false;if(f.search&&!(`${item.name} ${item.notes} ${item.store} ${item.category}`.toLowerCase().includes(f.search)))return false;if(f.mode==='pending'&&item.done)return false;if(f.mode==='done'&&!item.done)return false;return true}))}
function formatPriority(p){return p==='Alta'?'high':p==='Normal'?'normal':'low'}
function updateStats(){const total=items.length,done=items.filter(i=>i.done).length,pending=total-done;els.totalItems.textContent=total;els.doneItems.textContent=done;els.pendingItems.textContent=pending}
function render(){const list=filteredItems(),{store}=getFilters();els.list.innerHTML='';els.emptyState.classList.toggle('hidden',list.length!==0);els.visibleCount.textContent=`${list.length} ${list.length===1?'item':'itens'}`;els.selectedStoreText.textContent=store?`Loja destacada: ${store}`:'Sem loja selecionada.';updateStats();list.forEach(item=>{const card=document.createElement('article');card.className=`item-card ${item.done?'done':''} ${store&&item.store===store?'highlight':''}`;card.innerHTML=`<button class="check-btn" aria-label="Marcar comprado"></button><div class="item-main"><div class="item-title-row"><div class="item-title">${e(item.name)}</div><span class="pill store">${e(item.store)}</span><span class="pill ${formatPriority(item.priority)}">${e(item.priority)}</span></div><div class="item-meta"><span>Qtd: ${item.qty}</span><span>${e(item.category)}</span><span>${item.done?'Comprado':'Por comprar'}</span></div>${item.notes?`<div class="item-notes">${e(item.notes)}</div>`:''}</div><div class="item-actions"><button class="mini-btn toggle" title="Marcar">${item.done?'↺':'✓'}</button><button class="mini-btn delete" title="Apagar">🗑</button></div>`;card.querySelector('.check-btn').addEventListener('click',()=>toggleDone(item.id));card.querySelector('.toggle').addEventListener('click',()=>toggleDone(item.id));card.querySelector('.delete').addEventListener('click',()=>removeItem(item.id));els.list.appendChild(card)})}
function e(t){return String(t).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
els.addBtn.addEventListener('click',addItem);els.clearDoneBtn.addEventListener('click',clearDone);els.clearAllBtn.addEventListener('click',clearAll);els.filterStore.addEventListener('change',render);els.filterCategory.addEventListener('change',render);els.searchInput.addEventListener('input',render);els.showMode.addEventListener('change',render);els.themeToggle.addEventListener('click',toggleTheme);els.itemInput.addEventListener('keydown',e=>{if(e.key==='Enter')addItem()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});
els.installBtn.addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else{alert('No iPhone: abre no Safari e escolhe "Adicionar ao ecrã principal".')}})
if('serviceWorker' in navigator){window.addEventListener('load',()=>{navigator.serviceWorker.register('./sw.js').catch(()=>{})})}
applyTheme();render();
